#!/bin/bash

echo "🚀 Chat Widget Service Setup Instructions"
echo "========================================"
echo ""
echo "Project structure has been created successfully!"
echo ""
echo "📁 Apps:"
echo "  - Backend (NestJS):     apps/backend"
echo "  - Widget (React):       apps/widget"  
echo "  - Admin Dashboard:      apps/admin-dashboard"
echo ""
echo "📦 Shared Packages:"
echo "  - UI Components:        packages/ui"
echo "  - ESLint Config:        packages/eslint-config-custom"
echo "  - TypeScript Config:    packages/tsconfig"
echo ""
echo "🔧 To install dependencies and run the project:"
echo ""
echo "1. Install dependencies:"
echo "   pnpm install"
echo ""
echo "2. Start all development servers:"
echo "   pnpm dev"
echo ""
echo "   This will start:"
echo "   - Backend API:          http://localhost:3001"
echo "   - Widget:               http://localhost:5173"
echo "   - Admin Dashboard:      http://localhost:5174"
echo ""
echo "🎨 Features included:"
echo "  ✅ Tailwind CSS configured"
echo "  ✅ TypeScript setup"
echo "  ✅ ESLint configuration"
echo "  ✅ Monorepo with pnpm workspaces"
echo "  ✅ Basic UI components"
echo "  ✅ Sample chat widget interface"
echo "  ✅ Admin dashboard with routing"
echo ""
echo "📋 Next step: Run 'pnpm install' when network is stable"
